[package]
name = "nazad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.1"
serde = "1.0.160"
serde_json = "1.0.96"
chrono = "0.4.24"
